
{{- define "{{{.Project}}}.rules" -}}
{{- $serviceName := include "{{{.Project}}}.name" .default -}}
  {{- range .hosts }}
    - host: {{ . }}
      http:
        paths:
          - backend:
              serviceName: {{ $serviceName }}
              servicePort: http
            path: //api/sample-project
  {{- end }}
{{- end -}}
{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "{{{.Project}}}.fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
{{- if eq .Values.deploymentDestination "production" -}}
  {{- $hosts := tuple "vivintsky.com" "www.vivintsky.com" -}}
  {{- include "{{{.Project}}}.rules" (dict "hosts" $hosts "default" .) -}}
{{- else -}}
  {{- $host := printf "%s.platform.vivint.com" .Release.Namespace }}
  {{- $hostCloud := printf "%scloud.vivint.com" .Release.Namespace }}
  {{- $hosts := tuple $host $hostCloud -}}
  {{- include "{{{.Project}}}.rules" (dict "hosts" $hosts "default" .) -}}
{{- end }}

{{- end }}
