
{{- define "{{{.Service.Package}}}.rules" -}}
{{- $serviceName := include "{{{.Service.Package}}}.name" .default -}}
  {{- range .hosts }}
    - host: {{ . }}
      http:
        paths:
          - backend:
              serviceName: {{ $serviceName }}
              servicePort: http
            path: /api/{{{.Service.Package}}}
  {{- end }}
{{- end -}}
{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "{{{.Service.Package}}}.fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
{{- if eq .Values.deploymentDestination "production" -}}
  {{- $hosts := tuple "{{{.Chart.Domain}}}" "www.{{{.Chart.Domain}}}" -}}
  {{- include "{{{.Service.Package}}}.rules" (dict "hosts" $hosts "default" .) -}}
{{- else -}}
  {{- $host := printf "%s.{{{.Chart.Domain}}}" .Release.Namespace }}
  {{- $hosts := tuple $host -}}
  {{- include "{{{.Service.Package}}}.rules" (dict "hosts" $hosts "default" .) -}}
{{- end }}

{{- end }}
