
apiVersion: v1
kind: Service
metadata:
  name: {{ include "{{{.Service.Package}}}.name" . }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  type: ClusterIP 
  ports:
  - name: http
    port: 3000
  selector:
    app: {{ include "{{{.Service.Package}}}.name" . }}
  sessionAffinity: None
status:
  loadBalancer: {}

