global:
 image:
  tag: latest

env:
  LOG_LEVEL: INFO
  GOMAXPROCS: '2'
  LOG_JSON: 'true'

resources:
    limits:
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 5Mi

deploymentDestination: ""

{{{.Project}}}:
    image:
      registry: tp-artifactory.vivint.com:5000
      repository: sample-project
ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
fullnameOverride: "{{{.Project}}}"
nameOverride: ""

minReplicas: 1
maxReplicas: 1
