version: '3'
services:
  app:
    build: ""
    ports:
      - "{{ .service.GrpcPort }}:{{ .service.GrpcPort }}"
{{if .service.EnableHttp }}      - "{{ .service.HttpPort }}:{{ .service.HttpPort }}"{{end}}